export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTOLOGIN_SUCCESS = 'AUTOLOGIN_SUCCESS';
export const AUTOLOGIN_FAIL = 'AUTOLOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const GET_ALL_SECTIONS_REQUEST = "GET_ALL_SECTIONS_REQUEST";
export const GET_ALL_SECTIONS_SUCCESS = "GET_ALL_SECTIONS_SUCCESS";
export const GET_ALL_SECTIONS_FAIL = "GET_ALL_SECTIONS_FAIL";
export const CREATE_SECTION = 'CREATE_SECTION';
export const REMOVE_SECTION = 'REMOVE_SECTION';

export const GET_ALL_SHOPS_REQUEST = "GET_ALL_SHOPS_REQUEST";
export const GET_ALL_SHOPS_SUCCESS = "GET_ALL_SHOPS_SUCCESS";
export const GET_ALL_SHOPS_FAIL = "GET_ALL_SHOPS_FAIL";
export const CREATE_SHOP = 'CREATE_SHOP';
export const REMOVE_SHOP = 'REMOVE_SHOP';