export const GET_SECTIONS = 'GET_SECTIONS';
export const CREATE_SECTION = 'CREATE_SECTION';
export const REMOVE_SECTION = 'REMOVE_SECTION';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTOLOGIN_SUCCESS = 'AUTOLOGIN_SUCCESS';
export const AUTOLOGIN_FAIL = 'AUTOLOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

export const GET_ALL_SECTIONS_REQUEST = "GET_ALL_SECTIONS_REQUEST";
export const GET_ALL_SECTIONS_SUCCESS = "GET_ALL_SECTIONS_SUCCESS";
export const GET_ALL_SECTIONS_FAIL = "GET_ALL_SECTIONS_FAIL";